# NUMPY
# ARRAY (List of elements)
### 
## 1-1D ARRAY
#### i-1D Array row wise 

In [45]:
# 1D array are called vectors OR lIST
# 1D array row wise
import numpy as np
a=np.array([[1,2,3,4,5]])
b=np.array(["H","a","r","i","s"," ","K","h","a","n"])
a,b

(array([[1, 2, 3, 4, 5]]),
 array(['H', 'a', 'r', 'i', 's', ' ', 'K', 'h', 'a', 'n'], dtype='<U1'))

#### ii-1D array column wise

In [38]:
import numpy as np
a=np.array([[1],[2],[3],[4],[5]])
b=np.array([["H"],["a"],["r"],["i"],["s"],["  "],["K"],["h"],["a"],["n"]])
a, b

(array([[1],
        [2],
        [3],
        [4],
        [5]]),
 array([['H'],
        ['a'],
        ['r'],
        ['i'],
        ['s'],
        ['  '],
        ['K'],
        ['h'],
        ['a'],
        ['n']], dtype='<U2'))

#### iii-zeros ki Array

In [56]:
d=np.zeros(2)
d

array([0., 0.])

#### iv-Ones ki array

In [58]:
d=np.ones(2)
d

array([1., 1.])

#### v-Array with range of elements

In [61]:
e=np.arange(6)
e

array([0, 1, 2, 3, 4, 5])

#### vi-Array with range from one number to another

In [64]:
e=np.arange(3,19)
e

array([ 3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18])

#### vii-Array with range and step size

In [65]:
e=np.arange(5,50,5)
e

array([ 5, 10, 15, 20, 25, 30, 35, 40, 45])

#### viii-Linearly spacced arrays

In [71]:
e=np.linspace(2,20,num=10)
e

array([ 2.,  4.,  6.,  8., 10., 12., 14., 16., 18., 20.])

#### ix-Specifying data types in array

In [72]:
e=np.ones(6,dtype=np.int8)
e

array([1, 1, 1, 1, 1, 1], dtype=int8)

In [73]:
e=np.ones(6,dtype=np.float64)
e

array([1., 1., 1., 1., 1., 1.])

## 2-2D Array
#### i-(2D Array  are called matrix) OR (List of Lists)

In [2]:
import numpy as np
b=np.array([[1,2,3,4,5],[6,7,8,9,10]])
b

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [3]:
import numpy as np
b=np.array([[1,2,3,4,5],[6,7,8,9,10],[11,12,13,14,15]])
b

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15]])

#### ii zeros ki 2d array

In [75]:
a=np.zeros((4,6))
a

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

#### iii-Ones ki 2d array

In [76]:
a=np.ones((2,6))
a

array([[1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.]])

## Type of Array

In [21]:
type(a)

numpy.ndarray

## Length of Array

In [39]:
len(a),len(b)

(5, 10)

## Indexing in Array

In [42]:
# indexing of 1st array
a[0]

array([1])

In [47]:
# indexing of 2nd array
b[0]

'H'

In [48]:
# printing whole array
b[0:]

array(['H', 'a', 'r', 'i', 's', ' ', 'K', 'h', 'a', 'n'], dtype='<U1')

## Array atributes
- Dimensions are called axis

In [54]:
c=np.array([[4,4,4],[5,5,5]])
c
# - first axis has length 2
# -second axis has length 3

array([[4, 4, 4],
       [5, 5, 5]])

# 3D Array
### For 3D or higher array the term tensor is used
#### i- making and rehaping 3D array

In [82]:
a=np.arange(24).reshape(2,3,4)
a

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [83]:
a=np.arange(30).reshape(2,3,5)
a

array([[[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14]],

       [[15, 16, 17, 18, 19],
        [20, 21, 22, 23, 24],
        [25, 26, 27, 28, 29]]])